"""Pydantic data models — single source of truth for all data shapes."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class TumorResponse(str, Enum):
    COMPLETE = "complete"
    PARTIAL = "partial"
    STABLE = "stable"
    PROGRESSION = "progression"


class RiskTolerance(str, Enum):
    CONSERVATIVE = "conservative"
    BALANCED = "balanced"
    AGGRESSIVE = "aggressive"


class PatientFeatures(StrictModel):
    age: int
    sex: str
    condition: str


class OARFeature(StrictModel):
    type: str
    distance_to_tumor_mm: float | None = None


class CaseFeatures(StrictModel):
    tumor_type: str
    target_volume_cc: float
    prescription_gy: float | None = None
    fractions: int | None = None
    oars: list[OARFeature] = Field(default_factory=list)


class PlanningVariables(StrictModel):
    algorithm: str | None = None
    arcs: int | None = None
    arc_type: str | None = None
    ptv_margin_mm: float | None = None
    oar_prv_margins: dict[str, float] = Field(default_factory=dict)
    target_priority: str | None = None
    normal_tissue_priority: str | None = None
    modulation_level: str | None = None


class OARResult(StrictModel):
    type: str
    dmax_gy: float | None = None
    d0_2_gy: float | None = None
    d0_5_gy: float | None = None


class PlanResults(StrictModel):
    ci: float | None = None
    gi: float | None = None
    v12_cc: float | None = None
    mu: float | None = None
    coverage_percent: float | None = None
    oar_results: list[OARResult] = Field(default_factory=list)


class HistoricalPlan(StrictModel):
    case_id: str
    patient_features: PatientFeatures
    case_features: CaseFeatures
    planning_variables: PlanningVariables = Field(default_factory=PlanningVariables)
    results: PlanResults = Field(default_factory=PlanResults)
    physician: str


class Patient(HistoricalPlan):
    """Demo patient record in the shared historical-plan schema."""


class PastCase(HistoricalPlan):
    """Historical case record in the shared historical-plan schema."""


class PhysicianPreferences(StrictModel):
    """Preference profile, populated incrementally by Agent 3 from feedback.

    All signal fields are optional so a fresh `{"physician": "..."}` record still
    validates; Agent 3 fills them in over time (Loop 1 of the self-improvement).
    """

    physician: str
    favors_lower_mu: bool | None = None
    prioritizes_oar_sparing: bool | None = None
    favors_target_coverage: bool | None = None
    preferred_technique: str | None = None
    risk_tolerance: RiskTolerance | None = None
    notes: list[str] = Field(default_factory=list)
    signals: dict[str, Any] = Field(default_factory=dict)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class CandidatePlan(HistoricalPlan):
    """Plan generated by Agent 1."""

    rationale: str | None = None
    source_case_ids: list[str] = Field(default_factory=list)


class ChallengedPlan(CandidatePlan):
    """Plan critiqued by Agent 2."""

    risk_score: float = Field(ge=0.0, le=1.0)
    challenge: str
    selected_for_review: bool = False


class PhysicianChoice(StrictModel):
    physician: str
    run_id: str
    chosen_plan_id: str
    liked: str
    disliked: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class SideEffect(StrictModel):
    name: str
    grade: int = Field(ge=1, le=5)
    notes: str | None = None


class TreatmentOutcome(StrictModel):
    patient_id: str
    plan_id: str
    physician_id: str
    tumor_response: TumorResponse
    side_effects: list[SideEffect] = Field(default_factory=list)
    would_reuse_plan: bool
    outcome_weight: float = Field(ge=0.0, le=1.0, default=0.0)
    notes: str | None = None
    logged_at: datetime = Field(default_factory=datetime.utcnow)


class PipelineState(StrictModel):
    run_id: str
    patient_id: str
    physician_id: str
    status: str
    candidates: list[CandidatePlan] = Field(default_factory=list)
    challenged: list[ChallengedPlan] = Field(default_factory=list)
    top_two: list[ChallengedPlan] = Field(default_factory=list)
    chosen_plan_id: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)


# --- API request / response models ---


class GeneratePlansRequest(StrictModel):
    patient_id: str
    physician_id: str


class GeneratePlansResponse(StrictModel):
    run_id: str
    top_two: list[ChallengedPlan]


class PhysicianFeedbackRequest(StrictModel):
    run_id: str
    physician_id: str
    chosen_plan_id: str
    liked: str
    disliked: str


class PhysicianFeedbackResponse(StrictModel):
    physician: str
    updated_preferences: PhysicianPreferences


class LogOutcomeRequest(StrictModel):
    patient_id: str
    plan_id: str
    physician_id: str
    tumor_response: TumorResponse
    side_effects: list[SideEffect] = Field(default_factory=list)
    would_reuse_plan: bool
    notes: str | None = None


class LogOutcomeResponse(StrictModel):
    outcome: TreatmentOutcome
    case_id: str
