"""Pydantic data models — single source of truth for all data shapes."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class Technique(str, Enum):
    VMAT = "VMAT"
    IMRT = "IMRT"
    SBRT = "SBRT"
    THREE_D_CONFORMAL = "3D-CRT"


class TumorResponse(str, Enum):
    COMPLETE = "complete"
    PARTIAL = "partial"
    STABLE = "stable"
    PROGRESSION = "progression"


class Patient(BaseModel):
    patient_id: str
    age: int
    sex: str
    diagnosis: str
    tumor_location: str
    tumor_volume_cc: float
    kps_score: int = Field(ge=0, le=100, description="Karnofsky Performance Status")
    prior_surgery: bool = False
    prior_chemo: bool = False
    notes: str | None = None


class PlanMetrics(BaseModel):
    conformity_index: float | None = None
    homogeneity_index: float | None = None
    monitor_units: float | None = None
    optic_apparatus_dmax_gy: float | None = None
    brainstem_dmax_gy: float | None = None
    ptv_coverage_percent: float | None = None


class TreatmentPlan(BaseModel):
    plan_id: str
    total_dose_gy: float
    fractions: int
    technique: Technique
    beam_angles: list[float]
    metrics: PlanMetrics = Field(default_factory=PlanMetrics)
    rationale: str | None = None


class CandidatePlan(TreatmentPlan):
    """Plan generated by Agent 1."""


class ChallengedPlan(CandidatePlan):
    """Plan critiqued by Agent 2."""

    risk_score: float = Field(ge=0.0, le=1.0)
    challenge: str
    selected_for_review: bool = False


class PhysicianPreferences(BaseModel):
    physician_id: str
    favors_lower_mu: bool = False
    favors_higher_coverage: bool = False
    favors_fewer_fractions: bool = False
    risk_tolerance: str = "moderate"
    technique_preferences: list[Technique] = Field(default_factory=list)
    notes: str | None = None
    updated_at: datetime | None = None


class PhysicianChoice(BaseModel):
    physician_id: str
    run_id: str
    chosen_plan_id: str
    liked: str
    disliked: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class SideEffect(BaseModel):
    name: str
    grade: int = Field(ge=1, le=5)
    notes: str | None = None


class TreatmentOutcome(BaseModel):
    patient_id: str
    plan_id: str
    physician_id: str
    tumor_response: TumorResponse
    side_effects: list[SideEffect] = Field(default_factory=list)
    would_reuse_plan: bool
    outcome_weight: float = Field(ge=0.0, le=1.0, default=0.0)
    notes: str | None = None
    logged_at: datetime = Field(default_factory=datetime.utcnow)


class PastCase(BaseModel):
    case_id: str
    patient: Patient
    plan: TreatmentPlan
    outcome: TreatmentOutcome | None = None
    outcome_weight: float = Field(ge=0.0, le=1.0, default=1.0)
    physician_id: str


class PipelineState(BaseModel):
    run_id: str
    patient_id: str
    physician_id: str
    status: str
    candidates: list[CandidatePlan] = Field(default_factory=list)
    challenged: list[ChallengedPlan] = Field(default_factory=list)
    top_two: list[ChallengedPlan] = Field(default_factory=list)
    chosen_plan_id: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)


# --- API request / response models ---


class GeneratePlansRequest(BaseModel):
    patient_id: str
    physician_id: str


class GeneratePlansResponse(BaseModel):
    run_id: str
    top_two: list[ChallengedPlan]


class PhysicianFeedbackRequest(BaseModel):
    run_id: str
    physician_id: str
    chosen_plan_id: str
    liked: str
    disliked: str


class PhysicianFeedbackResponse(BaseModel):
    physician_id: str
    updated_preferences: PhysicianPreferences


class LogOutcomeRequest(BaseModel):
    patient_id: str
    plan_id: str
    physician_id: str
    tumor_response: TumorResponse
    side_effects: list[SideEffect] = Field(default_factory=list)
    would_reuse_plan: bool
    notes: str | None = None


class LogOutcomeResponse(BaseModel):
    outcome: TreatmentOutcome
    case_id: str
